//! Envelope construction: `SizedDecision` → `PreparedOrderEnvelope`.
//!
//! This is the missing Phase 5 piece (handoff spec section 3) that assembles a
//! signed, serialized order envelope from a fully-sized intent decision. The
//! envelope is what `load_or_prepare_attempt` persists and what
//! `IntlClobCopyAdapter::submit_exact_envelope` later reconstructs.
//!
//! ## Why this module exists
//!
//! Nothing in the repository previously built a real `PreparedOrderEnvelope`
//! from an actual signing operation — only test helpers
//! (`reconcile.rs:851`'s `envelope(salt)` function) did. A production path
//! needs:
//!
//! 1. Build a `SignableOrder` via the SDK's `limit_order()` builder
//!    (`canary_run.rs:177`'s `build_signable_order` already proves the exact
//!    builder DSL for FAK orders).
//! 2. Sign it **exactly once** via `client.sign(signer, signable)`.
//! 3. Compute `expected_taker_order_id` via `venue::order_hash::expected_order_id`
//!    (offline once the exchange address is resolved).
//! 4. Serialize the `SignedOrder` to `signed_order_json` via the SDK's
//!    `Serialize` impl.
//! 5. Return a `PreparedOrderEnvelope` ready for `load_or_prepare_attempt`.
//!
//! The signed order is never rebuilt: a second sign with a fresh salt would
//! produce a different order hash, defeating `load_or_prepare_attempt`'s
//! idempotency guarantee (blueprint invariant #5). The salt is generated by
//! the SDK's configured `salt_generator` (defaults to a deterministic
//! randomness source), so it is only stable when the signer's salt generator
//! is pinned — in practice the envelope is persisted on first attempt and
//! never re-prepared for the same `(intent_id, attempt_number)`.

use std::str::FromStr;

use alloy::primitives::U256;
use polymarket_client_sdk_v2::{
    auth::{state::Authenticated, Normal, Signer},
    clob::{
        types::{OrderType, Side as SdkSide},
        Client,
    },
};

use crate::{
    copytrading::{execute::SizedDecision, reconcile::PreparedOrderEnvelope},
    venue::order_hash::{self, ExchangeAddresses},
};

/// The signer + authenticated client pair needed to prepare one envelope.
///
/// `S` is any [`Signer`] implementation (typically `LocalSigner`). This
/// mirrors `canary_run`'s `signer()` return (`impl Signer + Clone`), but
/// accepts it explicitly here so the preparer does not own the key.
#[derive(Clone, Debug)]
pub struct EnvelopePreparer<'a, S: Signer> {
    pub client: &'a Client<Authenticated<Normal>>,
    pub signer: &'a S,
}

/// The result of envelope preparation. Contains the fully-serializable
/// `PreparedOrderEnvelope` plus the in-memory `SignedOrder` (needed by the
/// caller for audit — e.g. verifying the salt is stable). The `SignedOrder`
/// is never persisted; only its JSON form is.
#[derive(Debug)]
pub struct PreparedEnvelope {
    pub envelope: PreparedOrderEnvelope,
    pub signed_order: polymarket_client_sdk_v2::clob::types::SignedOrder,
}

impl<'a, S: Signer> EnvelopePreparer<'a, S> {
    /// Builds, signs, and serializes one FAK order envelope from a
    /// [`SizedDecision`].
    ///
    /// The salt is generated by the SDK's configured salt generator (set at
    /// authentication time). The signed order is serialized immediately via
    /// `serde_json::to_string(&signed_order)` — the SDK's manual `Serialize`
    /// impl (`clob/types/mod.rs:811`) — and never rebuilt.
    ///
    /// `expected_taker_order_id` is computed offline via
    /// [`order_hash::expected_order_id`] and formatted with
    /// [`order_hash::format_order_id`], matching the SDK's own `sign()`
    /// path that computes this hash internally but never returns it.
    pub async fn prepare(
        &self,
        decision: &SizedDecision,
    ) -> Result<PreparedEnvelope, PrepareError> {
        let token_id =
            U256::from_str(&decision.token_id).map_err(|_| PrepareError::InvalidTokenId)?;
        let side = match decision.side {
            crate::copytrading::execute::Side::Buy => SdkSide::Buy,
            crate::copytrading::execute::Side::Sell => SdkSide::Sell,
        };

        // Step 1: Build the SignableOrder. The SDK's `limit_order()` builder
        // handles tick-size validation, size alignment, and V1/V2 version
        // negotiation (neg-risk resolution). This is the exact same DSL that
        // canary_run.rs::build_signable_order uses.
        let signable = self
            .client
            .limit_order()
            .token_id(token_id)
            .side(side)
            .price(decision.limit_price)
            .size(decision.qty)
            .order_type(OrderType::FAK)
            .build()
            .await
            .map_err(PrepareError::OrderBuilding)?;

        // Step 2: Sign exactly once (blueprint invariant #5 — never rebuild).
        let signed_order = self
            .client
            .sign(self.signer, signable)
            .await
            .map_err(PrepareError::OrderSigning)?;

        // Step 3: Compute the expected order ID offline (no venue call).
        let expected_hash = {
            let token_id_match = match &signed_order.payload {
                polymarket_client_sdk_v2::clob::types::OrderPayload::V2(p) => p.order.tokenId,
                polymarket_client_sdk_v2::clob::types::OrderPayload::V1(p) => p.order.tokenId,
                _ => return Err(PrepareError::UnsupportedPayloadVersion),
            };
            let neg_risk_resp = self
                .client
                .neg_risk(token_id_match)
                .await
                .map_err(PrepareError::NegRiskQuery)?;
            let config = polymarket_client_sdk_v2::contract_config(
                polymarket_client_sdk_v2::POLYGON,
                neg_risk_resp.neg_risk,
            )
            .ok_or(PrepareError::MissingContractConfig)?;
            let exchanges = ExchangeAddresses {
                v1: config.exchange,
                v2: config.exchange_v2,
            };
            order_hash::expected_order_id(
                &signed_order.payload,
                &exchanges,
                polymarket_client_sdk_v2::POLYGON,
            )
            .map_err(PrepareError::OrderHash)?
        };
        let expected_taker_order_id = order_hash::format_order_id(expected_hash);

        // Step 4: Serialize the signed order (SDK's manual Serialize impl).
        let signed_order_json =
            serde_json::to_string(&signed_order).map_err(|_| PrepareError::OrderSerialization)?;

        // Step 5: Assemble the envelope.
        let envelope = PreparedOrderEnvelope {
            token_id: decision.token_id.clone(),
            side: decision.side.as_str().to_owned(),
            price: decision.limit_price.to_string(),
            size: decision.qty.to_string(),
            salt: extract_salt(&signed_order).unwrap_or(0),
            order_type: "FAK".to_owned(),
            expected_taker_order_id,
            signed_order_json,
        };

        Ok(PreparedEnvelope {
            envelope,
            signed_order,
        })
    }
}

/// Extracts the salt from a signed order for audit logging.
/// Returns 0 if the payload version is unsupported (should not happen in practice).
fn extract_salt(signed: &polymarket_client_sdk_v2::clob::types::SignedOrder) -> Option<u64> {
    let salt_u256 = match &signed.payload {
        polymarket_client_sdk_v2::clob::types::OrderPayload::V2(p) => Some(p.order.salt),
        polymarket_client_sdk_v2::clob::types::OrderPayload::V1(p) => Some(p.order.salt),
        _ => None,
    }?;
    let salt: u64 = salt_u256.try_into().ok()?;
    Some(salt)
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloy::primitives::{Address, Signature, B256, U256};
    use polymarket_client_sdk_v2::{
        auth::ApiKey,
        clob::types::{OrderPayload, OrderSignature, OrderType, SignedOrder},
    };

    #[test]
    fn extract_salt_reads_v2_salt_as_u64() {
        let mut order = polymarket_client_sdk_v2::clob::types::OrderV2::default();
        order.salt = U256::from(42u64);
        order.maker = Address::from_str("0x1111111111111111111111111111111111111111").unwrap();
        order.signer = Address::from_str("0x2222222222222222222222222222222222222222").unwrap();
        order.tokenId = U256::from(1u64);
        order.timestamp = U256::from(1u64);
        order.metadata = B256::ZERO;
        order.builder = B256::ZERO;
        let payload = OrderPayload::new(order, U256::from(0u64));
        let signature = Signature::from_str(concat!(
            "0x1111111111111111111111111111111111111111111111111111111111111111",
            "2222222222222222222222222222222222222222222222222222222222222222",
            "1b"
        ))
        .unwrap();
        let owner: ApiKey = "550e8400-e29b-41d4-a716-446655440000".parse().unwrap();
        let signed = SignedOrder::builder()
            .payload(payload)
            .signature(OrderSignature::Ecdsa(signature))
            .order_type(OrderType::FAK)
            .owner(owner)
            .build();
        assert_eq!(extract_salt(&signed), Some(42));
    }
}

/// Errors from envelope preparation.
#[derive(Debug)]
pub enum PrepareError {
    InvalidTokenId,
    OrderBuilding(polymarket_client_sdk_v2::error::Error),
    OrderSigning(polymarket_client_sdk_v2::error::Error),
    NegRiskQuery(polymarket_client_sdk_v2::error::Error),
    MissingContractConfig,
    UnsupportedPayloadVersion,
    OrderHash(crate::venue::order_hash::OrderHashError),
    OrderSerialization,
}

impl std::fmt::Display for PrepareError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::InvalidTokenId => write!(f, "invalid outcome token ID in decision"),
            Self::OrderBuilding(source) => write!(f, "order building failed: {source}"),
            Self::OrderSigning(source) => write!(f, "order signing failed: {source}"),
            Self::NegRiskQuery(source) => write!(f, "neg-risk query failed: {source}"),
            Self::MissingContractConfig => {
                write!(f, "no contract config for the resolved chain/neg-risk")
            }
            Self::UnsupportedPayloadVersion => write!(f, "unsupported order payload version"),
            Self::OrderHash(e) => write!(f, "offline order hash failed: {e}"),
            Self::OrderSerialization => write!(f, "failed to serialize signed order to JSON"),
        }
    }
}

impl std::error::Error for PrepareError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::OrderBuilding(source)
            | Self::OrderSigning(source)
            | Self::NegRiskQuery(source) => Some(source),
            Self::OrderHash(e) => Some(e),
            _ => None,
        }
    }
}
